name: kids_audio_app
description: A simple Flutter app for kids with audio and images.
version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1
  audioplayers: ^5.2.1
  sqflite: ^2.3.0
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true

  assets:
    - assets/twinkle.mp3
    - assets/macdonald.mp3
    - assets/wheels.mp3
    - assets/twinkle.jpg
    - assets/farm.jpg
    - assets/bus.png
